---
# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cygnet-test

---

# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: cygnet-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ipsps-tnd.kfon.ksitil.org:5000/nginx:v5

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cygnet-test
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort


---

